### ISSUE TITLE
Built wheel files and their availability on PyPI

### ISSUE THREAD

**Issue by fridex** [rapidsai/integration#178]
Hi everyone,

following the medium article and PyPI package description [1, 2] I would like to ask if there is any plan to reevaluate publishing built wheel files to PyPI.

I see this repo is watched just by 3 people so hopefully, this issue finds some response. Thanks in advance.

[1] https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472
[2] https://pypi.org/project/rapidsai/

**Comment by kkraus14** [comment]
Hi @fridex there's currently no plans for reevaluating building manylinux compatible wheels. We're following the ongoing work in the very exciting pip package solving / resolving work that's ongoing in the community, but until there's a way for pip to handle native code packages it's infeasible for us to produce wheels.

**Comment by fridex** [comment]
@kkraus14 thanks for the response. In that case, do you plan to publish at least source distributions on PyPI? Do you have any plans on publishing your own index that could host non-manylinux compliant packages to bypass PyPI restrictions?

**Comment by kkraus14** [comment]
> In that case, do you plan to publish at least source distributions on PyPI?

We don't have any plans on publishing source distributions currently.

Publishing source distributions would imply being able to easily build everything needed to run our Python packages from source, which is quite non-trivial due to the amount of native code and native dependencies we have. We're working on making this more streamlined and straightforward but aren't quite there yet.

> Do you have any plans on publishing your own index that could host non-manylinux compliant packages to bypass PyPI restrictions?

We don't have any plans on publishing our own index currently. Static linking all of the native code dependencies would lead to unnecessarily huge packages and handling all of the native code dependencies gracefully via `pip` is infeasible for us as of right now.

**Comment by fridex** [comment]
@kkraus14 thanks for the info and replies. Please let me know if you'll do any changes to this position.

**Comment by sevagh** [comment]
Hi @fridex - we now have experimental pip wheel support for RAPIDS: https://rapids.ai/pip
