### ISSUE TITLE
Inconsistent conda environment

### ISSUE THREAD

**Issue by willprice** [rapidsai/integration#227]
Hi RAPIDSAI team,

Not sure where to file this one, but here goes.

I'm having trouble getting pytorch and cuml to play nice together in a conda environment.

```bash
$ conda create -n cuml-test python=3.8 pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge

$ conda activate cuml-test

$ conda install  -n rapids-0.18 -c rapidsai -c nvidia -c conda-forge -c defaults cuml=0.18 cudatoolkit=11.0
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

- rapidsai/linux-64::ucx==1.9.0+gcd9efd3=cuda11.0_0
- conda-forge/linux-64::libfaiss==1.6.3=h328c4c8_3_cuda
- rapidsai/linux-64::libcugraph==0.18.0=cuda11.0_g65ec965f_0
- rapidsai/linux-64::cugraph==0.18.0=py38_g65ec965f_0
- rapidsai/linux-64::cuml==0.18.0=cuda11.0_py38_gb5f59e005_0
- rapidsai/linux-64::ucx-py==0.18.0=py38_gcd9efd3_0
- rapidsai/linux-64::rapids==0.18.0=cuda11.0_py38_g334c31e_223
- rapidsai/linux-64::libcuml==0.18.0=cuda11.0_gb5f59e005_0
done


==> WARNING: A newer version of conda exists. <==
current version: 4.8.3
latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda

# All requested packages already installed.


$ conda list | grep -i cuml                                                      (cuml-test)
# packages in environment at /home/willprice/.conda/envs/cuml-test:
```

I cannot install cuml into this basic environment created by following the pytorch set up as described on https://pytorch.org/

Weirdly conda says that "all requested packages are already installed", except cuml isn't installed, as evidenced by the `conda list` command.

Any tips on how to get pytorch and cuml to play nicely?

Thanks

**Comment by kkraus14** [comment]
Hi @willprice, I'm guessing this is due to the mixing of conda channels between commands. In each command in addition to the packages being requested, it needs to look at the dependency tree and all of the packages installed to come to some resolution. I'd suggest updating your command to a single `conda create` with all of the channels if possible:
```
conda create -n cuml-test python=3.8 pytorch torchvision torchaudio cudatoolkit=11.0 cuml=0.18 -c pytorch -c rapidsai -c nvidia -c conda-forge
```

**Comment by willprice** [comment]
Hi @kkraus14,
Thanks for the advice, that seems to resolve the issue. But what if I wanted to install cuML into an environment I've already created? I was under the impression that conda should be able to find a set of packages that don't lead to inconsistencies when I try and install a new package if I specify a set of channels that would enable such a set of packages to be found. I don't really understand why the fresh install works, but installing cuML into an existing env doesn't.

**Comment by kkraus14** [comment]
@willprice in that case, just make sure to include all of the conda channels in every install command. I.e. something like `conda install -c pytorch -c rapidsai -c nvidia -c conda-forge -c defaults cuml=0.18`. While cuml doesn't need anything from the pytorch channel, conda will evaluate and try to solve the entire environment and if all of the channels aren't specified it doesn't have the information needed to properly solve.

Alternatively, I would highly recommend using a `.condarc` file to manage the channels instead of passing them on every command (https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html)

**Comment by willprice** [comment]
Ah, that makes sense--for some reason it didn't occur to me that I'd also need to include the `pytorch` channel, but of course you are right. Thank you for your patient explanation.

**Comment by kkraus14** [comment]
My pleasure, closing as this is now resolved!
